# Generated by Django 5.2.10 on 2026-01-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='The Japanese sentence', null=True, verbose_name='content')),
                ('mean', models.TextField(blank=True, help_text='Meaning in Vietnamese', null=True, verbose_name='meaning')),
                ('trans', models.TextField(blank=True, help_text='Transcription/Reading', null=True, verbose_name='transcription')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'example',
                'verbose_name_plural': 'examples',
                'ordering': ['-created_at'],
            },
        ),
    ]
