# Generated by Django 5.2 on 2026-01-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lession_name",
                    models.TextField(
                        blank=True,
                        help_text="Name of the lesson",
                        null=True,
                        verbose_name="lesson name",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "lesson",
                "verbose_name_plural": "lessons",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_name",
                    models.TextField(
                        blank=True,
                        help_text="Name of the unit",
                        null=True,
                        verbose_name="unit name",
                    ),
                ),
                (
                    "lession_id",
                    models.TextField(
                        blank=True,
                        help_text="ID of the parent lesson",
                        null=True,
                        verbose_name="lesson id",
                    ),
                ),
                (
                    "total",
                    models.TextField(
                        blank=True,
                        help_text="Total number of items in this unit",
                        null=True,
                        verbose_name="total items",
                    ),
                ),
                (
                    "unit_type",
                    models.TextField(
                        blank=True,
                        help_text="Type of unit (vocabulary, grammar, kanji, mixed)",
                        null=True,
                        verbose_name="unit type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "unit",
                "verbose_name_plural": "units",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="UnitGrammarDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_id",
                    models.TextField(
                        blank=True,
                        help_text="ID of the unit",
                        null=True,
                        verbose_name="unit id",
                    ),
                ),
                (
                    "grammar_id",
                    models.TextField(
                        blank=True,
                        help_text="ID of the grammar point",
                        null=True,
                        verbose_name="grammar id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "unit grammar detail",
                "verbose_name_plural": "unit grammar details",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="UnitKanjiDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_id",
                    models.TextField(
                        blank=True,
                        help_text="ID of the unit",
                        null=True,
                        verbose_name="unit id",
                    ),
                ),
                (
                    "kanji_id",
                    models.TextField(
                        blank=True,
                        help_text="ID of the kanji",
                        null=True,
                        verbose_name="kanji id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "unit kanji detail",
                "verbose_name_plural": "unit kanji details",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="UnitWordDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_id",
                    models.TextField(
                        blank=True,
                        help_text="ID of the unit",
                        null=True,
                        verbose_name="unit id",
                    ),
                ),
                (
                    "word_id",
                    models.TextField(
                        blank=True,
                        help_text="ID of the word",
                        null=True,
                        verbose_name="word id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "unit word detail",
                "verbose_name_plural": "unit word details",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="UserUnitProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_id",
                    models.TextField(
                        blank=True,
                        help_text="ID of the unit",
                        null=True,
                        verbose_name="unit id",
                    ),
                ),
                (
                    "progress",
                    models.TextField(
                        blank=True,
                        help_text="Progress value (e.g., percentage or status)",
                        null=True,
                        verbose_name="progress",
                    ),
                ),
                (
                    "completed_at",
                    models.TextField(
                        blank=True,
                        help_text="Completion timestamp",
                        null=True,
                        verbose_name="completed at",
                    ),
                ),
                (
                    "user_id",
                    models.TextField(
                        blank=True,
                        help_text="ID of the user",
                        null=True,
                        verbose_name="user id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "user unit progress",
                "verbose_name_plural": "user unit progresses",
                "ordering": ["id"],
            },
        ),
    ]
