# Generated by Django 5.2.10 on 2026-01-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userunitprogress',
            name='lession_id',
            field=models.TextField(blank=True, help_text='ID of the lesson (for easier querying by lesson)', null=True, verbose_name='lesson id'),
        ),
    ]
