# Generated by Django 5.2.10 on 2026-01-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_userunitprogress_lession_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, help_text='Name of the book', null=True, verbose_name='name')),
                ('level', models.TextField(blank=True, help_text='JLPT level (1-5)', null=True, verbose_name='level')),
                ('total_word', models.TextField(blank=True, help_text='Total number of words in this book', null=True, verbose_name='total word')),
                ('version', models.TextField(blank=True, help_text='Version of the book', null=True, verbose_name='version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'book set',
                'verbose_name_plural': 'book sets',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BookSetUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_set_id', models.TextField(blank=True, help_text='ID of the parent book set', null=True, verbose_name='book set id')),
                ('name', models.TextField(blank=True, help_text='Name of the unit/section', null=True, verbose_name='name')),
                ('total_word', models.TextField(blank=True, help_text='Total number of words in this unit', null=True, verbose_name='total word')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'book set unit',
                'verbose_name_plural': 'book set units',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BookSetUnitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.TextField(blank=True, help_text='ID of the book set unit', null=True, verbose_name='unit id')),
                ('word_id', models.TextField(blank=True, help_text='ID of the word', null=True, verbose_name='word id')),
                ('sub_word', models.TextField(blank=True, help_text='Sub word (if any)', null=True, verbose_name='sub word')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'book set unit detail',
                'verbose_name_plural': 'book set unit details',
                'ordering': ['id'],
            },
        ),
    ]
