# Generated by Django 5.2.10 on 2026-02-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_bookset_booksetunit_booksetunitdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='level',
            field=models.CharField(blank=True, help_text='JLPT level (N5, N4, N3, N2, N1)', max_length=5, null=True, verbose_name='JLPT level'),
        ),
        migrations.AddField(
            model_name='unit',
            name='level',
            field=models.CharField(blank=True, help_text='JLPT level (N5, N4, N3, N2, N1)', max_length=5, null=True, verbose_name='JLPT level'),
        ),
    ]
