# Generated by Django 5.2.10 on 2026-02-01 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_add_level_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookSet',
        ),
        migrations.DeleteModel(
            name='BookSetUnit',
        ),
        migrations.DeleteModel(
            name='BookSetUnitDetail',
        ),
    ]
