# Generated by Django 5.2.10 on 2026-02-11 16:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_normalize_word_unit_type_to_vocabulary'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitAnkiCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.TextField(db_index=True, help_text='ID of the unit', verbose_name='unit id')),
                ('user_id', models.TextField(db_index=True, help_text='ID of the user', verbose_name='user id')),
                ('item_type', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('kanji', 'Kanji')], help_text='Type of linked learning item', max_length=20, verbose_name='item type')),
                ('item_id', models.TextField(help_text='ID of the linked vocabulary/grammar/kanji record', verbose_name='item id')),
                ('state', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('relearning', 'Relearning'), ('review', 'Review')], db_index=True, default='new', max_length=20, verbose_name='card state')),
                ('step_index', models.PositiveSmallIntegerField(default=0, help_text='Current learning or relearning step index', verbose_name='learning step index')),
                ('interval_days', models.PositiveIntegerField(default=0, help_text='Next review interval in days when card is in review state', verbose_name='interval (days)')),
                ('ease_factor', models.FloatField(default=2.5, help_text='SM-2 ease factor used to grow intervals', verbose_name='ease factor')),
                ('reps', models.PositiveIntegerField(default=0, help_text='Total number of times this card was answered', verbose_name='review repetitions')),
                ('lapses', models.PositiveIntegerField(default=0, help_text='How many times a review card failed (Again)', verbose_name='lapses')),
                ('due_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this card should appear again', verbose_name='due at')),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='last reviewed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'unit anki card',
                'verbose_name_plural': 'unit anki cards',
                'ordering': ['due_at', 'id'],
                'indexes': [models.Index(fields=['user_id', 'unit_id', 'due_at'], name='learning_un_user_id_99f5a0_idx'), models.Index(fields=['user_id', 'unit_id', 'state'], name='learning_un_user_id_e14659_idx')],
                'constraints': [models.UniqueConstraint(fields=('unit_id', 'user_id', 'item_type', 'item_id'), name='learning_unitankicard_unique_user_unit_item')],
            },
        ),
        migrations.CreateModel(
            name='UnitAnkiReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('again', 'Again'), ('hard', 'Hard'), ('good', 'Good'), ('easy', 'Easy')], max_length=10, verbose_name='rating')),
                ('previous_state', models.CharField(max_length=20, verbose_name='previous state')),
                ('next_state', models.CharField(max_length=20, verbose_name='next state')),
                ('previous_interval_days', models.PositiveIntegerField(default=0, verbose_name='previous interval (days)')),
                ('next_interval_days', models.PositiveIntegerField(default=0, verbose_name='next interval (days)')),
                ('previous_ease_factor', models.FloatField(default=2.5, verbose_name='previous ease factor')),
                ('next_ease_factor', models.FloatField(default=2.5, verbose_name='next ease factor')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, help_text='Optional client-side answer time', null=True, verbose_name='response time (ms)')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='reviewed at')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='learning.unitankicard', verbose_name='anki card')),
            ],
            options={
                'verbose_name': 'unit anki review log',
                'verbose_name_plural': 'unit anki review logs',
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
