# Generated by Django 5.2.11 on 2026-02-17 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("N6", "Beginner"),
                            ("N5", "N5 - Basic"),
                            ("N4", "N4 - Elementary"),
                            ("N3", "N3 - Intermediate"),
                            ("N2", "N2 - Pre-Advanced"),
                            ("N1", "N1 - Advanced"),
                        ],
                        db_index=True,
                        max_length=2,
                    ),
                ),
                ("exam_id", models.BigIntegerField(db_index=True)),
                ("section_code", models.SlugField(blank=True, default="")),
                (
                    "subcategory_code",
                    models.SlugField(blank=True, default="", max_length=80),
                ),
                ("exam_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In progress"),
                            ("SUBMITTED", "Submitted"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        db_index=True,
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("total_items", models.PositiveIntegerField(default=0)),
                ("answered_items", models.PositiveIntegerField(default=0)),
                ("correct_items", models.PositiveIntegerField(default=0)),
                ("score", models.FloatField(default=0)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "practice attempt",
                "verbose_name_plural": "practice attempts",
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PracticeAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_item_id", models.BigIntegerField(db_index=True)),
                ("selected_answer", models.IntegerField(blank=True, null=True)),
                ("correct_answer", models.IntegerField(blank=True, null=True)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="practice.practiceattempt",
                    ),
                ),
            ],
            options={
                "verbose_name": "practice answer",
                "verbose_name_plural": "practice answers",
                "ordering": ["attempt_id", "question_item_id", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="practiceattempt",
            index=models.Index(
                fields=["user", "level", "exam_id"],
                name="practice_pr_user_id_869e72_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="practiceattempt",
            index=models.Index(
                fields=["user", "status", "started_at"],
                name="practice_pr_user_id_5b7ab8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="practiceanswer",
            index=models.Index(
                fields=["attempt", "updated_at"], name="practice_pr_attempt_01ba90_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="practiceanswer",
            constraint=models.UniqueConstraint(
                fields=("attempt", "question_item_id"),
                name="practice_answer_unique_attempt_item",
            ),
        ),
    ]
