# Generated by Django 5.2.10 on 2026-01-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name for the user', max_length=50, verbose_name='display name'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('GOOGLE', 'Google'), ('FACEBOOK', 'Facebook')], default='EMAIL', max_length=20, verbose_name='login method'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], default='USER', max_length=10, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BANNED', 'Banned')], default='ACTIVE', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, help_text='URL to user avatar image', null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('N6', 'Beginner'), ('N5', 'N5 - Basic'), ('N4', 'N4 - Elementary'), ('N3', 'N3 - Intermediate'), ('N2', 'N2 - Pre-Advanced'), ('N1', 'N1 - Advanced')], default='N5', help_text='Current JLPT level target', max_length=2, verbose_name='JLPT level'),
        ),
    ]
