# Generated by Django 5.2.10 on 2026-02-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_nickname_user_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('N6', 'Beginner'), ('N5', 'N5 - Basic'), ('N4', 'N4 - Elementary'), ('N3', 'N3 - Intermediate'), ('N2', 'N2 - Pre-Advanced'), ('N1', 'N1 - Advanced')], default='N6', help_text='Current JLPT level target', max_length=2, verbose_name='JLPT level'),
        ),
    ]
