# Generated by Django 5.2.10 on 2026-02-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_image_id',
            field=models.CharField(blank=True, help_text='Cloudflare Images ID for current avatar', max_length=128, null=True, verbose_name='avatar image id'),
        ),
    ]
