# Generated by Django 5.2.10 on 2026-01-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(blank=True, help_text='The Kanji character', max_length=10, null=True, verbose_name='kanji')),
                ('mean', models.TextField(blank=True, help_text='Meanings in Vietnamese', null=True, verbose_name='meaning')),
                ('level', models.IntegerField(blank=True, help_text='JLPT level as integer (5=N5, 4=N4, 3=N3, 2=N2, 1=N1)', null=True, verbose_name='JLPT level')),
                ('on', models.TextField(blank=True, help_text='Onyomi readings', null=True, verbose_name='onyomi')),
                ('kun', models.TextField(blank=True, help_text='Kunyomi readings', null=True, verbose_name='kunyomi')),
                ('img', models.TextField(blank=True, help_text='Image URL or path', null=True, verbose_name='image')),
                ('detail', models.TextField(blank=True, help_text='Detailed description', null=True, verbose_name='detail')),
                ('freq', models.CharField(blank=True, help_text='Frequency of appearance', max_length=100, null=True, verbose_name='frequency')),
                ('comp', models.TextField(blank=True, help_text='Components (string)', null=True, verbose_name='components')),
                ('stroke_count', models.IntegerField(blank=True, help_text='Number of strokes', null=True, verbose_name='stroke count')),
                ('compDetail', models.JSONField(blank=True, default=list, help_text='List of component objects [{h, w}]', null=True, verbose_name='component details')),
                ('examples', models.JSONField(blank=True, default=list, help_text='List of example objects [{h, m, p, w}]', null=True, verbose_name='examples')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'kanji',
                'verbose_name_plural': 'kanjis',
                'ordering': ['level', 'kanji'],
                'indexes': [models.Index(fields=['kanji', 'level'], name='kanjis_kanj_kanji_957c0f_idx')],
            },
        ),
    ]
