# Generated by Django 5.2.10 on 2026-01-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_word', models.CharField(db_index=True, max_length=100, verbose_name='Japanese word')),
                ('phonetic', models.CharField(blank=True, help_text='Hiragana/Katakana reading', max_length=200, verbose_name='phonetic reading')),
                ('short_mean', models.CharField(blank=True, help_text='Brief meaning summary', max_length=500, verbose_name='short meaning')),
                ('han', models.CharField(blank=True, help_text='Kanji characters', max_length=100, verbose_name='han/kanji')),
                ('grid', models.CharField(blank=True, help_text='Number of strokes', max_length=10, verbose_name='stroke count')),
                ('level', models.CharField(choices=[('N6', 'Beginner'), ('N5', 'N5 - Basic'), ('N4', 'N4 - Elementary'), ('N3', 'N3 - Intermediate'), ('N2', 'N2 - Pre-Advanced'), ('N1', 'N1 - Advanced')], db_index=True, default='N5', max_length=5, verbose_name='JLPT level')),
                ('mean', models.JSONField(blank=True, default=list, help_text='Array of meanings with examples: [{"mean": "...", "kind": "...", "examples": [...]}]', verbose_name='meanings')),
                ('opposite_word', models.JSONField(blank=True, default=list, help_text='Array of opposite words: ["word1", "word2"]', verbose_name='opposite words')),
                ('synsets', models.JSONField(blank=True, default=list, help_text='Array of synonym sets with definitions', verbose_name='synonym sets')),
                ('related_words', models.JSONField(blank=True, default=list, help_text='Array of related words', verbose_name='related words')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'word',
                'verbose_name_plural': 'words',
                'ordering': ['level', 'j_word'],
                'indexes': [models.Index(fields=['j_word', 'level'], name='vocabulary__j_word_9ed3d1_idx')],
            },
        ),
    ]
