# Generated by Django 5.2.10 on 2026-01-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='mean',
            field=models.JSONField(blank=True, default=list, help_text='Array of meanings with examples: [{"mean": "...", "kind": "...", "examples": [...]}]', null=True, verbose_name='meanings'),
        ),
        migrations.AlterField(
            model_name='word',
            name='opposite_word',
            field=models.JSONField(blank=True, default=list, help_text='Array of opposite words: ["word1", "word2"]', null=True, verbose_name='opposite words'),
        ),
        migrations.AlterField(
            model_name='word',
            name='related_words',
            field=models.JSONField(blank=True, default=list, help_text='Array of related words', null=True, verbose_name='related words'),
        ),
        migrations.AlterField(
            model_name='word',
            name='synsets',
            field=models.JSONField(blank=True, default=list, help_text='Array of synonym sets with definitions', null=True, verbose_name='synonym sets'),
        ),
    ]
