# Generated by Django 5.2.10 on 2026-01-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_word_mean_alter_word_opposite_word_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='grid',
            field=models.CharField(blank=True, help_text='Number of strokes', max_length=10, null=True, verbose_name='stroke count'),
        ),
        migrations.AlterField(
            model_name='word',
            name='han',
            field=models.CharField(blank=True, help_text='Kanji characters', max_length=100, null=True, verbose_name='han/kanji'),
        ),
        migrations.AlterField(
            model_name='word',
            name='short_mean',
            field=models.CharField(blank=True, help_text='Brief meaning summary', max_length=500, null=True, verbose_name='short meaning'),
        ),
    ]
