# Generated by Django 5.2.10 on 2026-01-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_alter_word_grid_alter_word_han_alter_word_short_mean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.CharField(blank=True, choices=[('N6', 'Beginner'), ('N5', 'N5 - Basic'), ('N4', 'N4 - Elementary'), ('N3', 'N3 - Intermediate'), ('N2', 'N2 - Pre-Advanced'), ('N1', 'N1 - Advanced')], db_index=True, default='N5', max_length=5, null=True, verbose_name='JLPT level'),
        ),
    ]
