# Generated by Django 5.2.10 on 2026-01-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_alter_word_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='phonetic',
            field=models.CharField(blank=True, help_text='Hiragana/Katakana reading', max_length=200, null=True, verbose_name='phonetic reading'),
        ),
    ]
