# Generated by Django 5.2.10 on 2026-01-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0005_alter_word_phonetic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='short_mean',
            field=models.TextField(blank=True, help_text='Brief meaning summary', null=True, verbose_name='short meaning'),
        ),
    ]
