# Generated by Django 5.2.11 on 2026-02-16 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="N4Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120)),
                ("name", models.CharField(max_length=200)),
                ("source_file", models.CharField(max_length=255, unique=True)),
                (
                    "source_kind",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("jlpt_level", models.PositiveSmallIntegerField(default=4)),
                ("time_limit_seconds", models.PositiveIntegerField(default=0)),
                ("question_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "N4 exam",
                "verbose_name_plural": "N4 exams",
                "ordering": ["subcategory__sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="N4Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "N4 section",
                "verbose_name_plural": "N4 sections",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="N4MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("LOCAL", "Local file"), ("REMOTE", "Remote URL")],
                        max_length=10,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Image"),
                            ("AUDIO", "Audio"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("source_url", models.TextField(blank=True, default="")),
                (
                    "source_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "source_basename",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("r2_key", models.CharField(max_length=500, unique=True)),
                ("public_url", models.TextField()),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("content_length", models.BigIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "N4 media asset",
                "verbose_name_plural": "N4 media assets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source_type", "media_type"],
                        name="n4_n4mediaa_source__04a61c_idx",
                    ),
                    models.Index(
                        fields=["source_basename"],
                        name="n4_n4mediaa_source__899ee8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="N4Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.BigIntegerField(db_index=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("kind", models.CharField(blank=True, default="", max_length=120)),
                ("title", models.TextField(blank=True, default="")),
                ("jlpt_level", models.PositiveSmallIntegerField(default=4)),
                ("score", models.FloatField(default=0)),
                ("scores", models.JSONField(blank=True, default=list)),
                ("correct_answers", models.JSONField(blank=True, default=list)),
                ("time_tracking", models.IntegerField(default=0)),
                ("source_import", models.JSONField(blank=True, default=dict)),
                ("raw_general", models.JSONField(blank=True, default=dict)),
                ("general_audio_url", models.TextField(blank=True, default="")),
                ("general_image_url", models.TextField(blank=True, default="")),
                ("general_txt_read", models.TextField(blank=True, default="")),
                ("general_text_read_en", models.TextField(blank=True, default="")),
                ("general_text_read_vn", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="n4.n4exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "N4 question",
                "verbose_name_plural": "N4 questions",
                "ordering": ["exam", "display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="N4QuestionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_order", models.PositiveIntegerField(default=0)),
                ("question_text", models.TextField(blank=True, default="")),
                ("image_url", models.TextField(blank=True, default="")),
                ("answers", models.JSONField(blank=True, default=list)),
                ("choose_answer", models.IntegerField(blank=True, null=True)),
                ("correct_answer", models.IntegerField(blank=True, null=True)),
                ("explain_en", models.TextField(blank=True, default="")),
                ("explain_vn", models.TextField(blank=True, default="")),
                ("raw_explain", models.JSONField(blank=True, default=dict)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="n4.n4question",
                    ),
                ),
            ],
            options={
                "verbose_name": "N4 question item",
                "verbose_name_plural": "N4 question items",
                "ordering": ["question", "item_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="N4Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80)),
                ("source_key", models.CharField(db_index=True, max_length=120)),
                ("name", models.CharField(max_length=150)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="n4.n4section",
                    ),
                ),
            ],
            options={
                "verbose_name": "N4 subcategory",
                "verbose_name_plural": "N4 subcategories",
                "ordering": ["section__sort_order", "sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="n4exam",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="n4.n4subcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="n4question",
            index=models.Index(
                fields=["exam", "kind"], name="n4_n4questi_exam_id_eb2816_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="n4question",
            index=models.Index(
                fields=["exam", "display_order"], name="n4_n4questi_exam_id_c7a0ef_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="n4question",
            unique_together={("exam", "display_order"), ("exam", "source_id")},
        ),
        migrations.AddIndex(
            model_name="n4questionitem",
            index=models.Index(
                fields=["question", "item_order"], name="n4_n4questi_questio_8e830f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="n4questionitem",
            unique_together={("question", "item_order")},
        ),
        migrations.AddIndex(
            model_name="n4subcategory",
            index=models.Index(
                fields=["section", "source_key"], name="n4_n4subcat_section_526431_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="n4subcategory",
            unique_together={("section", "code"), ("section", "source_key")},
        ),
        migrations.AddIndex(
            model_name="n4exam",
            index=models.Index(
                fields=["subcategory", "slug"], name="n4_n4exam_subcate_7ae816_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="n4exam",
            index=models.Index(
                fields=["source_kind"], name="n4_n4exam_source__da9d3f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="n4exam",
            unique_together={("subcategory", "slug")},
        ),
    ]
