# Generated by Django 5.2.10 on 2026-01-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, help_text='Grammar point title (e.g., あれ)', null=True, verbose_name='title')),
                ('mean', models.TextField(blank=True, help_text='Meaning in Vietnamese', null=True, verbose_name='meaning')),
                ('level', models.IntegerField(blank=True, help_text='JLPT level as integer (5=N5, 4=N4, 3=N3, 2=N2, 1=N1)', null=True, verbose_name='JLPT level')),
                ('note', models.TextField(blank=True, help_text='Additional notes', null=True, verbose_name='note')),
                ('structure', models.TextField(blank=True, help_text='Grammar structure/pattern', null=True, verbose_name='structure')),
                ('about', models.TextField(blank=True, help_text='Description about the grammar point', null=True, verbose_name='about')),
                ('fun_fact', models.JSONField(blank=True, default=list, help_text='List of fun facts', null=True, verbose_name='fun facts')),
                ('caution', models.JSONField(blank=True, default=list, help_text='List of caution notes', null=True, verbose_name='cautions')),
                ('examples', models.JSONField(blank=True, default=list, help_text='List of example sentences [{example, mean}]', null=True, verbose_name='examples')),
                ('synonyms', models.JSONField(blank=True, default=list, help_text='List of related grammar [{example, mean}]', null=True, verbose_name='synonyms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'grammar',
                'verbose_name_plural': 'grammars',
                'ordering': ['level', 'title'],
                'indexes': [models.Index(fields=['title', 'level'], name='grammar_gra_title_d5e0dc_idx')],
            },
        ),
    ]
